version: '3'

volumes:
  postgres_volume:
  redis-data:


services:
  pg:
    image: postgres:14-alpine3.17
    environment:
      - "POSTGRES_DB=${PG_DATABASE_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    networks:
      - auth-db-network

  migrator:
    build:
      context: .
      dockerfile: migration.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg
    networks:
      - auth-db-network

  redis:
    image: redis:7.2.6-alpine
    container_name: auth-cache-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/var/lib/redis/data
    networks:
      - auth-db-network

networks:
  auth-db-network:
    driver: bridge
